### ISSUE TITLE
Can you add support for the .NET Framework?

### ISSUE THREAD

**Issue by DamianMorozov** [nullfx/NullFX.CRC#13]
Please add support for .NET Framework versions 4.0/4.5/4.6/4.7/4.8.

**Comment by nullfx** [comment]
sorry been a busy week.  will add that to the next version here shortly.

**Comment by nullfx** [comment]
> Please add support for .NET Framework versions 4.0/4.5/4.6/4.7/4.8.

I've updated the csproj here and pushed the nuget package here on github and nuget.org (which should propagate shortly but may take some time).

Cheers!

**Comment by DamianMorozov** [comment]
Thank you. This solution is worked.

**Comment by nullfx** [comment]
Brilliant! glad it worked. again, sorry it took so long, I've had a super busy week.
