### ISSUE TITLE
NullFX.CRC.Crc16.ComputeChecksum(Crc16Algorithm.CcittKermit, bytes) gving wrong results

### ISSUE THREAD

**Issue by SysconNielsLucas** [nullfx/NullFX.CRC#23]
Hello, I try to use the Crc16Algorithm.CcittKermit, but its giving me wrong results.

```
var rawValue = 3218461.ToString();
var bytes = Encoding.UTF8.GetBytes(rawValue);
var raw = NullFX.CRC.Crc16.ComputeChecksum(Crc16Algorithm.CcittKermit, bytes);
var a = string.Format("0x{0:X}", NullFX.CRC.Crc16.ComputeChecksum(Crc16Algorithm.CcittKermit, bytes));
```
a result = 0xAAE0
But checking on https://crccalc.com/?crc=3218461&method=crc16&datatype=ascii&outtype=0 the result should be 0xE0AA

As you can see, the correct characters are there, just not in the right order and this happens for every input I throw at it. So my quickfix was just to do this: `var fixedValue = $"{a[0]}{a[1]}{a[4]}{a[5]}{a[2]}{a[3]}"`; But it would be nice if the correct output comes out of the ComputedCheckSum methods.

I am not sure if I am doing something wrong with the package or that there is a bug? I have the feeling I am doing something wrong, but I have no experience in this area.

EDIT: fix for ComputeChecksum
```
raw = SwapBytes(raw );
var a = string.Format("0x{0:X}", raw );

public static ushort SwapBytes(ushort x)
      {
          byte[] bytes = BitConverter.GetBytes(x);

          Array.Reverse(bytes);
          return BitConverter.ToUInt16(bytes, 0);
      }
```

**Comment by nullfx** [comment]
both the kermit and dnp implementations were returning the CRC as big endian.

Will be pushing an an update `v1.1.7` shortly that will resolve the issue

**Comment by SysconNielsLucas** [comment]
Thanks!
