### ISSUE TITLE
Variations of CRC

### ISSUE THREAD

**Issue by Aetherinox** [nullfx/NullFX.CRC#29]
I've tested out all of the algorithms, and I've been comparing them to CyberChef since that's the app I use the most (via https://gchq.github.io/CyberChef/)

Is CyberChef using a different type of CRC algo? Or am I missing a vital setting in yours. Because I've tested out about every variation of CRC16 I can, and I never get the values that I get in CyberChef.

However, CRC32 seems to be fine.

**Comment by Aetherinox** [comment]
Alright, it was a two step issue. One, I had an error in my hex string formatting. Second, your CRC-8 matches with CyberChef's CRC-8/DVB-S2. 

I've known about a few of the variations of CRC, but I went and looked at a total list and had no damn clue there's so many types.

The default for Cyber Chef is CRC 8 tab. Once I plugged those numbers in, I got the same result for CRC 8 in both programs.

Seriously had no clue there were so many. Sorry for the bother.

**Comment by nullfx** [comment]
🤣 it can be confusing for sure, glad you got it sorted, cheers!

here's another good crc website (with admittedly a lot more implementations that I have in the library): https://crccalc.com/

**Comment by Aetherinox** [comment]
Thanks.

That's actually crazy. The website I found yesterday showed that there was like 6 variants of CRC16. The website you sent says there's like 23 damn variants.

Never seen so many variants for a single hash algorithm.

Even CyberChef one gives you like 6 variants for CRC8, whereas with 16. 32 you only get one.
